#+TITLE:  Elisps a History - Character Back Stories
#+AUTHOR: John Hooks
#+EMAIL:  john@bitmachina.com
#+DATE:   <2016-09-29 Thu>
#+STARTUP: indent
#+STARTUP: hidestars

** The Origin

   /John McCarthy/

   The Author of Lisp Primitives.

** The Great Gnu

   /rms/

   The Author of the the first Elisps.

   Emacs born out of the war of the Lisp Machines and Symbolics.
   
** The Authors

   The creators of the Ancients and the Elisps.

** The Ancients

   The Builders of Lisps. Crafted by the Authors.

*** Nil

The First Ancient, before everything there was Nil.

*** The Seven Primitives

**** Quote
/The Patron of Data/
     
**** Atom
/Should I include it?/

**** Eq
/The Scales/
     
**** Car
/The Head/

Brother of Cdr.

**** Cdr
/The Tail/

Brother of Car.

**** Cons
/The Builder/

Builder of Lists. The first Primitive after Nil.
     
**** Cond
/The Pathfinder/

Choose the right path.
Divided the River List.

** And Or
** Set

** Lambda
   Priest of the Higher Order, located in the Forest of Funcall.
   Lives beneath trees of the forrest. Nomad

** Assoc
** Alist
** Mapcar
** Debugger

   /Lord of the Underword/

** Mark and Point
** The Kill Ring
** Quasi`Quote & Un,Quote
** Let
** Progn
** License

Copyright (C)  2016  John Hooks.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
