#+TITLE:  Elisps a History - Back Stories
#+AUTHOR: John Hooks
#+EMAIL:  john@bitmachina.com
#+DATE:   <2016-09-29 Thu>
#+STARTUP: indent
#+STARTUP: hidestars

** The Origin
   /John McCarthy/
   The Author of Lisp Primitives.

** The Great Gnu
   /rms/
   The Author of the the first Elisps in the Origin Forge.
   
** The River List
   A river, the source of which starts in the Inner Sanctuary of the
   Temple Nil surrounded by the mountain range Parens, it flows down
   a steep ravine to meander through the Forest of Funcall. After a
   dark journey through the forest, the waters empty into the many
   channels of the Delta Cond, of which, all reunite in the Sea of
   Eval.

** The Delta Cond
   Maybe Cond. The Delta Cond... A large delta with many channels
   The Primitive Cond died in an attempt to divide the River List.
   Maybe a battle with Cons.
   Thought the result is the Delta Cond at the mouth of the river.

** The Sea of Eval
   A sea into which the River List flows.

** The Buffer
   A bare plain on which the Elisps have wage great battles. 

** The Authors
   The creators of the Ancients and the Elisps.

** The Ancients
   The Builders of Lisps. Crafted by the Authors.

*** Nil
   The First Ancient, before everything there was Nil.

*** The Seven Primitives
**** Quote
     /The Protector of Data on the Sea of Eval/
     
**** Atom
     /Should I include it?/

**** Eq
     /The Scale/
     
**** Car
     /The Headhunter/
     Brother of Cdr.

**** Cdr
     /The Follower/
     Brother of Car.

**** Cons
     /The Builder/
     Builder of Lists. The first Primitive after Nil.
     
**** Cond
    /The Guide/
    Choose the right path.
    Divided the River List.

** Setq

** Lambda
   Priest of the Higher Order, located in the Forest of Funcall.
   Lives beneath trees of the forrest. Nomad

** Assoc

** Alist

** Mapcar

** Debugger
   /Lord of the Underword/

** Quasi`Quote & Un,Quote
** License
Copyright (C)  2016  John Hooks.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
